lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
#    token_ttl: 3600
#    user_identity_field: username
#
#    encoder:
#        service: lexik_jwt_authentication.encoder.lcobucci
#        signature_algorithm: RS256
#
#    token_extractors:
#        authorization_header:
#            enabled: false
#
#        cookie:
#            enabled: true
#            name: BEARER
#    set_cookies:
#        BEARER: 
#            lifetime: null
#            samesite: lax
#            path: /
#            domain: null
#            secure: false
#            httpOnly: true
#