security:
    password_hashers:
        App\Entity\Client:
            algorithm: "auto"
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: "auto"
    enable_authenticator_manager: true
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: username
    firewalls:
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider